// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyUP4Dv1rBVQpD4D9-U3C48hRNUltkUUQ',
    appId: '1:600790015509:web:f625fbebb1577901f2381c',
    messagingSenderId: '600790015509',
    projectId: 'coopconnect-3eca5',
    authDomain: 'coopconnect-3eca5.firebaseapp.com',
    storageBucket: 'coopconnect-3eca5.firebasestorage.app',
    measurementId: 'G-RCV5RVNDG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFrNXjdbEdZv0ka7D4ao-07zuUHGUTid0',
    appId: '1:600790015509:android:88e9248ebd039d9bf2381c',
    messagingSenderId: '600790015509',
    projectId: 'coopconnect-3eca5',
    storageBucket: 'coopconnect-3eca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsKcbQg5wYxB1PvU4q_K3SvmIX5SA7YD0',
    appId: '1:600790015509:ios:adb56182a5d73861f2381c',
    messagingSenderId: '600790015509',
    projectId: 'coopconnect-3eca5',
    storageBucket: 'coopconnect-3eca5.firebasestorage.app',
    iosBundleId: 'com.example.cimalite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsKcbQg5wYxB1PvU4q_K3SvmIX5SA7YD0',
    appId: '1:600790015509:ios:adb56182a5d73861f2381c',
    messagingSenderId: '600790015509',
    projectId: 'coopconnect-3eca5',
    storageBucket: 'coopconnect-3eca5.firebasestorage.app',
    iosBundleId: 'com.example.cimalite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyUP4Dv1rBVQpD4D9-U3C48hRNUltkUUQ',
    appId: '1:600790015509:web:48ea4fda49eaf06df2381c',
    messagingSenderId: '600790015509',
    projectId: 'coopconnect-3eca5',
    authDomain: 'coopconnect-3eca5.firebaseapp.com',
    storageBucket: 'coopconnect-3eca5.firebasestorage.app',
    measurementId: 'G-31GW62SG75',
  );

}